import {strategyMarkup} from './strategies.js';
const app = document.querySelector('#app');
const esc = s => String(s??'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let chapters=[], readMode=false, completed=new Set();
try{completed=new Set(JSON.parse(localStorage.getItem('k8s-completed')||'[]'));}catch{}
const icons=['◈','⌘','▣','⧉','◎','⇄','⌁','⑂','↻','✓'];
function nav(active){document.querySelector('#chapters').innerHTML=chapters.map((c,i)=>`<a class="chapter-link ${c.id===active?'active':''}" href="#${c.id}/1" ${c.id===active?'aria-current="page"':''}><span class="num">${String(i+1).padStart(2,'0')}</span><span>${esc(c.short)}</span><span class="done">${completed.has(c.id)?'✓':''}</span></a>`).join('');}
function home(){nav();const total=chapters.reduce((n,c)=>n+c.slides.length,0);app.classList.remove('read-mode');app.innerHTML=`<section class="hero"><div><div class="eyebrow">FROM FRONTEND TO INFRASTRUCTURE</div><h1>화면 너머의 세상,<br><em>Kubernetes</em>로<br>한 걸음 더.</h1><p>브라우저의 요청은 어디로 갈까요?<br>익숙한 프론트엔드에서 출발해, 내 앱이 실행되는<br>인프라까지 함께 이해하는 10주 스터디.</p><div class="tags"><span class="tag">네트워크 지식 없이 시작</span><span class="tag">로컬 실습</span><span class="tag">공식 문서 기반</span></div><div class="hero-actions"><a class="primary" href="#01/1">첫 번째 수업 시작하기 <span>↗</span></a><a class="secondary" href="#curriculum">전체 커리큘럼 ↓</a></div></div><div class="hero-art" aria-label="요청은 브라우저에서 Gateway를 거쳐 Service의 대상 Pod로 전달됩니다"><div class="art-label">A REQUEST'S JOURNEY</div><div class="art-browser">◉ &nbsp; Browser</div><div class="art-arrow">↓</div><div class="art-gateway">Gateway / Ingress</div><div class="art-arrow">↓</div><div class="art-cluster"><small>SERVICE → TARGET PODS</small><div class="art-pods"><span>▣ Pod 01</span><span>▣ Pod 02</span><span>▣ Pod 03</span></div></div><div class="art-caption">요청 흐름을 단순화한 개념도</div></div></section><div class="stats"><div class="stat"><strong>10</strong><span>주차별 챕터</span></div><div class="stat"><strong>${total}</strong><span>학습 슬라이드</span></div><div class="stat"><strong>01</strong><span>이어지는 실습 프로젝트</span></div><div class="stat"><strong>${completed.size}<small>/10</small></strong><span>학습 완료</span></div></div><section id="curriculum"><div class="section-heading"><div><div class="eyebrow">YOUR LEARNING PATH</div><h2>하나씩 연결되는, 열 번의 수업</h2><p>개념을 읽고, 직접 실행하고, 나의 말로 설명해 보세요.</p></div><span>챕터를 선택해 학습 시작 ↗</span></div><div class="course-grid">${chapters.map((c,i)=>`<a class="course-card" href="#${c.id}/1"><div class="card-top"><span class="week">WEEK ${c.id}</span><span class="card-icon">${icons[i]}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="card-bottom"><span>${c.slides.length} SLIDES · ${esc(c.type)}</span><span>${completed.has(c.id)?'완료 ✓':'학습하기 ↗'}</span></div></a>`).join('')}</div></section><div class="study-note"><strong>이 스터디의 약속</strong><span>도메인·VIP는 예시로 이해하고, 접속은 localhost로 실습합니다. Argo CD는 개념만 소개합니다. 각 챕터의 실습 파일과 공식 문서를 함께 제공합니다.</span></div>`;if(location.hash==='#curriculum')document.querySelector('#curriculum').scrollIntoView();}
function slideMarkup(s,i){return `<article class="slide" id="slide-${i+1}"><div class="kicker">${esc(s.kind||'CONCEPT')} <span> / ${String(i+1).padStart(2,'0')}</span></div><h2>${esc(s.title)}</h2>${s.lead?`<p class="lead">${esc(s.lead)}</p>`:''}${s.strategy?strategyMarkup(s.strategy):''}${s.cards?`<div class="concept-grid">${s.cards.map(([t,d])=>`<div class="concept"><strong>${esc(t)}</strong><p>${esc(d)}</p></div>`).join('')}</div>`:''}${s.flow?`<div class="flow">${s.flow.map((t,j)=>`${j?'<span class="flow-arrow">→</span>':''}<div class="flow-box">${esc(t)}</div>`).join('')}</div>`:''}${s.bullets?`<ul>${s.bullets.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}${s.code?`<div class="code-wrap"><button class="copy" data-copy="${i}">복사</button><pre><code>${esc(s.code)}</code></pre></div>`:''}${s.callout?`<div class="callout">${esc(s.callout)}</div>`:''}${s.answer?`<details class="answer"><summary>정답과 해설 보기</summary><p>${esc(s.answer)}</p></details>`:''}${s.file?`<a class="download" href="labs/${esc(s.file)}" download>실습 파일 다운로드 · ${esc(s.file)} ↓</a>`:''}</article>`;}
function notesMarkup(s,c){return `<details class="notes" ${readMode?'open':''}><summary>함께 읽는 해설 · 실습 안내</summary><div class="notes-body">${(s.notes||[]).map(p=>`<p>${esc(p)}</p>`).join('')}${s.expected?`<h3>예상 결과</h3><p>${esc(s.expected)}</p>`:''}${s.trouble?`<h3>막혔을 때</h3><p>${esc(s.trouble)}</p>`:''}<h3>공식 문서에서 더 읽기</h3><div class="sources">${(s.sources||c.sources).map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)} ↗</a>`).join('')}</div></div></details>`;}
function current(){const [id,n]=location.hash.slice(1).split('/');return {c:chapters.find(c=>c.id===id),n:Math.max(0,(parseInt(n)||1)-1)};}
function render(){document.querySelector('.sidebar').classList.remove('open');const {c,n:raw}=current();if(!c){document.body.classList.remove('presenting');home();return;}const n=Math.min(raw,c.slides.length-1);nav(c.id);app.classList.toggle('read-mode',readMode);app.innerHTML=`<div class="lesson-top"><div><div class="eyebrow">WEEK ${c.id} · ${esc(c.type)}</div><h1>${esc(c.title)}</h1></div><div class="lesson-tools"><button class="secondary" id="reading">${readMode?'슬라이드 보기':'전체 읽기'}</button><button class="secondary" id="present">${document.body.classList.contains('presenting')?'발표 종료':'발표 모드 ⛶'}</button></div></div>${readMode?c.slides.map((s,i)=>slideMarkup(s,i)+notesMarkup(s,c)).join(''):slideMarkup(c.slides[n],n)+`<div class="slide-nav"><button class="secondary" id="prev" ${n===0?'disabled':''}>← 이전</button><span class="slide-count">${String(n+1).padStart(2,'0')} / ${String(c.slides.length).padStart(2,'0')} &nbsp; · &nbsp; ← → 키로 이동</span><button class="primary" id="next" ${n===c.slides.length-1?'disabled':''}>다음 →</button></div><div class="slide-track"><div style="width:${(n+1)/c.slides.length*100}%"></div></div>`+notesMarkup(c.slides[n],c)}<div class="toc" aria-label="슬라이드 목록">${c.slides.map((s,i)=>`<a class="${i===n?'current':''}" href="#${c.id}/${i+1}">${i+1}. ${esc(s.title)}</a>`).join('')}</div><div class="complete-row"><span>이 챕터를 설명할 수 있게 되었다면 완료를 표시해 주세요.</span><button id="complete" class="secondary">${completed.has(c.id)?'학습 완료 ✓':'학습 완료 표시'}</button></div>`;
document.querySelector('#reading').onclick=()=>{readMode=!readMode;document.body.classList.remove('presenting');render();};document.querySelector('#present').onclick=()=>{readMode=false;document.body.classList.toggle('presenting');render();};document.querySelector('#prev')?.addEventListener('click',()=>move(-1));document.querySelector('#next')?.addEventListener('click',()=>move(1));document.querySelector('#complete').onclick=()=>{completed.has(c.id)?completed.delete(c.id):completed.add(c.id);try{localStorage.setItem('k8s-completed',JSON.stringify([...completed]));}catch{}render();};document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(c.slides[Number(b.dataset.copy)].code);b.textContent='복사됨 ✓';}catch{b.textContent='코드를 선택해 복사';}});}
function move(d){const {c,n}=current();if(c&&!readMode){const next=Math.min(c.slides.length-1,Math.max(0,n+d));location.hash=`${c.id}/${next+1}`;}}
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,location.hash==='#curriculum'?document.querySelector('#curriculum').getBoundingClientRect().top+scrollY:0);});
document.addEventListener('keydown',e=>{if(e.target.closest('button,input,textarea,summary,a'))return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='Escape'){document.body.classList.remove('presenting');render();}});
try{const response=await fetch('catalog.json');if(!response.ok)throw new Error();chapters=await response.json();render();}catch{app.innerHTML='<p class="loading">학습 자료를 불러오지 못했습니다. 서버에서 열었는지 확인하고 새로고침해 주세요.</p>';}
