const pod=(v)=>`<span class="pod-chip v${v}">▣ v${v}</span>`;
const group=(oldCount,newCount)=>`<div class="pod-group">${pod(1).repeat(oldCount)}${pod(2).repeat(newCount)}</div>`;
const stages={
 rolling:[['01 · 기존 버전',group(3,0),'v1이 요청을 처리합니다.'],['02 · 새 Pod 준비',group(3,1),'Ready 확인 후 기존 Pod를 줄입니다.'],['03 · 점진적 교체',group(1,2),'v1과 v2가 함께 요청을 받습니다.'],['04 · 교체 완료',group(0,3),'모든 Pod가 v2로 바뀝니다.']],
 bluegreen:[['01 · 별도 환경 준비',`<div class="env blue"><b>Blue · 운영 요청 100%</b>${group(3,0)}</div><div class="env green"><b>Green · 검증 요청만</b>${group(0,3)}</div>`,'새 환경을 먼저 검증합니다.'],['02 · 목적지 전환',`<div class="traffic-node">사용자 요청</div><div class="switch-arrow">↓ 운영 경로 전환</div><div class="env green"><b>Green · 신규 요청 100%</b>${group(0,3)}</div>`,'운영 라우팅 대상을 Green으로 바꿉니다.'],['03 · 이전 환경 보관',`<div class="env blue muted-env"><b>Blue · 복귀 대비</b>${group(3,0)}</div><div class="env green"><b>Green · 운영 중</b>${group(0,3)}</div>`,'안정화 후 이전 환경을 정리합니다.']],
 canary:[['01 · 작은 비율',traffic(90,10),'새 버전을 일부 요청으로 검증합니다.'],['02 · 점진적 확대',traffic(50,50),'오류율·지연 등을 보고 확대합니다.'],['03 · 전체 전환',traffic(0,100),'검증을 통과하면 전체를 전환합니다.']]
};
function traffic(a,b){return `<div class="traffic-node">사용자 요청</div><div class="switch-arrow">↓ 가중치 라우팅</div><div class="traffic-bar"><span class="old-traffic" style="flex:${a||0.01}">${a?a+'%':''}</span><span class="new-traffic" style="flex:${b}">${b}%</span></div><div class="traffic-targets"><span class="v1">v1 Service · ${a}%</span><span class="v2">v2 Service · ${b}%</span></div>`;}
export function strategyMarkup(type){return `<div class="strategy-legend"><span class="v1">■ v1 · 기존 버전</span><span class="v2">■ v2 · 새 버전</span><span>왼쪽에서 오른쪽으로 진행 →</span></div><div class="strategy-stages ${type}">${stages[type].map(([title,body,note])=>`<section class="strategy-stage"><h3>${title}</h3>${body}<p>${note}</p></section>`).join('')}</div><p class="diagram-caption">${type==='rolling'?'Pod 개수는 예시입니다. 연결별 요청 비율을 보장하지 않습니다.':type==='bluegreen'?'전환 그림은 논리적 경로를 표현합니다. 기존 연결과 설정 전파에는 시간이 걸릴 수 있습니다.':'표시된 비율은 목표 가중치입니다. 적은 요청 수에서는 관측 비율이 다를 수 있습니다.'}</p>`;}
